### ISSUE TITLE
How to get rectangular outline on custom activity?

### ISSUE THREAD

**Issue by kiaanpillay** [PDF417/pdf417-android#24]
When scanning a PDF417 in the default activity it creates a rectangular outline in the ui to show the user where it is currently scanning, how am I able to get this with a custom activity?

**Comment by culoi** [comment]
Hi @kiaanpillay 

To get rectangular outline you need to use [Metadata listener](https://github.com/PDF417/pdf417-android#-obtaining-various-metadata-with-metadatalistener). 
First you need to enable receiving of detection location

```
ms.setDetectionMetadataAllowed(true);
```

DetectionMetadata contains DetectorResult which is null if object detection has failed and non-null otherwise. 
``` 
DetectorResult dr = ((DetectionMetadata) metadata).getDetectionResult();
            if (dr == null) {
```
Let's assume that we have a QuadViewManager which can display animated frame around detected object
Animate frame to default location if detection has failed
``` 
mQuadViewManager.animateQuadToDefaultPosition();
            } else if (dr instanceof QuadDetectorResult) {
```
Otherwise, animate frame to detected location
```
mQuadViewManager.animateQuadToDetectionPosition((QuadDetectorResult) dr);
```

Please refer to our [CustomUI demo app](https://github.com/PDF417/pdf417-android/tree/master/Pdf417MobiDemo/pdf417MobiDemoCustomUI) 

Best regards,
Ivan

**Comment by kiaanpillay** [comment]
Excellent. Thank you
